### ISSUE TITLE
'Permission denied (publickey)'

### ISSUE THREAD

**Issue by Shawg** [thoughtbot/proteus-jekyll#19]
When trying to clone the repo using the getting started instructions, 
```
git clone git@github.com:thoughtbot/proteus-jekyll.git your-project-folder
```
yields the error: 
```
Cloning into 'your-project-folder'...
Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```
But using 
```
git clone https://github.com/thoughtbot/proteus-jekyll.git your-project-folder
```
works fine.

**Comment by joshuaogle** [comment]
This usually happens when you haven't [set up a publickey with Github](https://help.github.com/articles/error-permission-denied-publickey/). You would be able to clone with HTTPS, but not using SSH. Also, if you have registered keys on one computer but are using a different one, you would need to set up that one too.

If you have done that and are able to clone other projects using SSH, then there might be something else wrong, but it's good to check that first.

**Comment by Shawg** [comment]
Perfect, that did it!
It also fixed [this](https://github.com/thoughtbot/proteus/issues/9) issue in the proteus repository.

**Comment by joshuaogle** [comment]
Glad to hear it! Closed that one too
