### ISSUE TITLE
Rendering content from a collection item

### ISSUE THREAD

**Issue by areohbe** [thoughtbot/proteus-jekyll#27]
I'm using a `collection` to build out the documentation on a site for a piece of open source software but it appears I'm unable render the markdown from each item in the collection correctly.

My collection name is `_docs` and this code below is in my `docs.haml` file. (I am using the 'Scroll on Page' pattern from [Refills](http://refills.bourbon.io/) for reference.)

```
%section
  .scroll-on-page
    %aside#scroll-on-page-top
      {% for doc in site.docs %}
      %a.scroll-on-page-link{:href => "#{{ doc.shortname }}"} {{ doc.title }}
      {% endfor %}
    %article
      {% for doc in site.docs %}
      %section
        %h4#{{ doc.shortname }} {{ doc.title }}
        .content
          {{ doc.content }}
      {% endfor %}
```

When I attempt to build my site I get an `Illegal nesting: nesting within plain text is illegal.` error.

I've also tried replacing `{{ doc.content }}` with `{{ doc.output }}`  and `{{ doc.content | markdownify }}` to attempt to render markdown correctly but still received the same error.

Is there something obvious I am overlooking? Or should I be using something other than collections to achieve this?

**Comment by joshuaogle** [comment]
Hi Rob, I found a few ways to get something similar working using the example post included in the repo. I had to remove the `highlight` section, but then it rendered fine. Are you using that example by any chance?

It looks like it will render the highlighting, but any indentation or string interpolation (like `"#{name}"`) will throw it off. I think this is probably an issue to bring up with the `jekyll-haml` gem, but let's find a fix here too. I'll investigate alternatives to that gem to see if we can accommodate both.

If you need the highlighting (I think that might be the case since it says 'docs'), then switching to HTML works fine. If you don't need the highlighting then I think anything else you are using in markdown should render without a problem.

**Comment by areohbe** [comment]
Hey Josh - The files in my `_docs` collection currently just have lorem ipsum in without any additional markdown markup in them. 😕

**Comment by joshuaogle** [comment]
I was afraid you'd say that. Well at least we found out there's an issue with the highlighter too. I did change some of your markup to be a little simpler, but I don't think it's causing your issue. Here's what I had just in case:

```
%section
  .scroll-on-page
    %aside#scroll-on-page-top
      {% for doc in site.docs %}
      %a.scroll-on-page-link{href: doc.shortname}
        {{ doc.title }}
      {% endfor %}

    %article
      {% for doc in site.docs %}
      %section
        %h4{id: doc.shortname }
          {{ doc.title }}

        .content
          {{ doc.content }}
      {% endfor %}
```

The only other thing I can think of is to try [this different Haml converter that has been suggested in PR#26](#26).

If that doesn't work though, I'd suggest switching to HTML. Sometimes the errors that Jekyll gives you aren't super helpful, so it's hard to say where the problem is coming from.

**Comment by areohbe** [comment]
I ended up using the changes in PR #26 and the converted the files in my collection to `.haml` instead of `.markdown` and was able to build the site successfully. While I would prefer to be writing content in markdown, it's not a bad solution since the rest of my templates are written in `haml` as well.

**Comment by areohbe** [comment]
Also, when I replaced my code with the recommendation above, I got a ` undefined local variable or method 'doc'` error.

**Comment by areohbe** [comment]
Erg, unfortunately, the aforementioned method is only rendering the first block of content inside the `.haml` file correctly. Subsequent elements are getting rendered outside the intended `<section>`. 😕

**Comment by tysongach** [comment]
This project is no longer being actively maintained.
